CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `password` varchar(100) NOT NULL,
  `real_name` varchar(50) DEFAULT NULL,
  `role` varchar(20) NOT NULL DEFAULT 'merchant',
  `must_change_password` boolean NOT NULL DEFAULT false,
  `disabled` boolean NOT NULL DEFAULT false,
  `disabled_time` datetime DEFAULT NULL,
  `deleted` boolean NOT NULL DEFAULT false,
  `deleted_time` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`),
  UNIQUE KEY `uk_phone` (`phone`)
);

CREATE TABLE IF NOT EXISTS `customer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `gender` tinyint DEFAULT 0,
  `birthday` date DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `deleted` boolean NOT NULL DEFAULT false,
  `deleted_time` datetime DEFAULT NULL,
  `deleted_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_phone` (`phone`)
);

CREATE TABLE IF NOT EXISTS `optometry_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `customer_id` bigint NOT NULL,
  `od_sph` decimal(5,2) DEFAULT NULL,
  `od_cyl` decimal(5,2) DEFAULT NULL,
  `od_axis` int DEFAULT NULL,
  `od_va` varchar(20) DEFAULT NULL,
  `os_sph` decimal(5,2) DEFAULT NULL,
  `os_cyl` decimal(5,2) DEFAULT NULL,
  `os_axis` int DEFAULT NULL,
  `os_va` varchar(20) DEFAULT NULL,
  `od_pd` decimal(5,1) DEFAULT NULL,
  `os_pd` decimal(5,1) DEFAULT NULL,
  `pd_far` decimal(5,1) DEFAULT NULL,
  `pd_near` decimal(5,1) DEFAULT NULL,
  `add_power` decimal(5,2) DEFAULT NULL,
  `optometrist_name` varchar(50) DEFAULT NULL,
  `exam_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` boolean NOT NULL DEFAULT false,
  `deleted_time` datetime DEFAULT NULL,
  `deleted_by` bigint DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `sales_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `record_no` varchar(50) NOT NULL,
  `customer_id` bigint NOT NULL,
  `optometry_id` bigint DEFAULT NULL,
  `frame_brand` varchar(100) DEFAULT NULL,
  `frame_model` varchar(100) DEFAULT NULL,
  `frame_price` decimal(10,2) DEFAULT 0.00,
  `lens_brand` varchar(100) DEFAULT NULL,
  `lens_params` varchar(200) DEFAULT NULL,
  `lens_price` decimal(10,2) DEFAULT 0.00,
  `total_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sales_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `operator_id` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` boolean NOT NULL DEFAULT false,
  `deleted_time` datetime DEFAULT NULL,
  `deleted_by` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
);
